import type { WorkflowState } from "@/features/workflow/types"

export const initialWorkflowState: WorkflowState = {
  tasks: [
    {
      id: "finalize-launch-day-captions",
      title: "Finalize launch-day captions",
      description: "Polish the launch captions, confirm product claims, and prepare the final platform-specific copy for approval.",
      clientId: "luma-skincare",
      clientName: "Luma Skincare",
      campaign: "Autumn Glow Launch",
      contentItem: "Autumn launch carousel",
      priority: "high",
      status: "in_progress",
      startDate: "Sep 23, 2026",
      dueDate: "Sep 25, 2026 · 10:30 AM",
      primaryOwner: { id: "maria", name: "Maria Reyes", initials: "MR", role: "Account Manager" },
      collaborators: [{ id: "kevin", name: "Kevin Lim", initials: "KL", role: "Copywriter" }],
      checklist: [
        { id: "claims", label: "Confirm approved product claims", completed: true },
        { id: "instagram", label: "Finalize Instagram caption", completed: true },
        { id: "facebook", label: "Adapt copy for Facebook", completed: false },
        { id: "links", label: "Verify campaign links", completed: false },
      ],
      comments: [
        { id: "comment-1", author: "Kevin Lim", initials: "KL", body: "Product claims are confirmed. I highlighted the final CTA options in the brief.", createdAt: "Today · 8:42 AM" },
      ],
      versions: [],
      activity: [
        { id: "activity-1", label: "Task moved to In progress", actor: "Maria Reyes", createdAt: "Today · 8:15 AM" },
        { id: "activity-2", label: "Kevin completed product-claim review", actor: "Kevin Lim", createdAt: "Today · 8:42 AM" },
      ],
    },
    {
      id: "upload-carousel-design-v2",
      title: "Upload carousel design V2",
      description: "Address the supervisor notes from V1 and upload the revised carousel with the approved typography and CTA treatment.",
      clientId: "northwind-coffee",
      clientName: "Northwind Coffee",
      campaign: "Cold Brew Stories",
      contentItem: "Cold brew founder story",
      priority: "urgent",
      status: "revision_requested",
      startDate: "Sep 22, 2026",
      dueDate: "Sep 25, 2026 · 1:00 PM",
      primaryOwner: { id: "maria", name: "Maria Reyes", initials: "MR", role: "Account Manager" },
      collaborators: [{ id: "anna", name: "Anna Cruz", initials: "AC", role: "Designer" }],
      checklist: [
        { id: "contrast", label: "Increase CTA contrast", completed: true },
        { id: "logo", label: "Correct logo safe area", completed: true },
        { id: "export", label: "Export revised carousel", completed: false },
      ],
      comments: [],
      versions: [
        {
          id: "northwind-v1",
          number: 1,
          status: "revision_requested",
          notes: "Initial carousel layout for the founder story.",
          submittedBy: "Maria Reyes",
          submittedById: "maria",
          submittedAt: "Sep 24, 2026 · 3:20 PM",
          files: [{ id: "carousel-v1", name: "northwind-carousel-v1.pdf", size: 4200000, type: "application/pdf" }],
          reviewComment: "Please increase CTA contrast and restore the logo safe area on slides 4–6.",
          reviewedBy: "Sarah Chen",
          reviewedAt: "Sep 24, 2026 · 4:05 PM",
        },
      ],
      activity: [
        { id: "activity-3", label: "Revision requested on V1", actor: "Sarah Chen", createdAt: "Yesterday · 4:05 PM" },
      ],
    },
    {
      id: "founder-story-reel",
      title: "Review founder story reel",
      description: "Review the final founder-story reel before it is approved for the October editorial schedule.",
      clientId: "harbor-and-pine",
      clientName: "Harbor & Pine",
      campaign: "Fall Editorial",
      contentItem: "October editorial reel",
      priority: "high",
      status: "for_review",
      startDate: "Sep 21, 2026",
      dueDate: "Sep 26, 2026 · 11:00 AM",
      primaryOwner: { id: "jordan", name: "Jordan Lee", initials: "JL", role: "Account Manager" },
      collaborators: [{ id: "noah", name: "Noah Kim", initials: "NK", role: "Video Editor" }],
      checklist: [
        { id: "captions", label: "Add burned-in captions", completed: true },
        { id: "audio", label: "Normalize audio", completed: true },
        { id: "export-reel", label: "Export final review file", completed: true },
      ],
      comments: [],
      versions: [
        {
          id: "harbor-v1",
          number: 1,
          status: "submitted",
          notes: "Final 30-second reel with captions and normalized audio.",
          submittedBy: "Jordan Lee",
          submittedById: "jordan",
          submittedAt: "Today · 9:18 AM",
          files: [{ id: "reel-v1", name: "harbor-founder-reel-v1.mp4", size: 18800000, type: "video/mp4" }],
        },
      ],
      activity: [{ id: "activity-4", label: "V1 submitted for review", actor: "Jordan Lee", createdAt: "Today · 9:18 AM" }],
    },
    {
      id: "prepare-campaign-performance-notes",
      title: "Prepare campaign performance notes",
      description: "Summarize the strongest campaign results, open questions, and talking points for the weekly client review.",
      clientId: "sunday-studio",
      clientName: "Sunday Studio",
      campaign: "Member Stories",
      contentItem: "September performance recap",
      priority: "medium",
      status: "todo",
      startDate: "Sep 25, 2026",
      dueDate: "Sep 25, 2026 · 5:00 PM",
      primaryOwner: { id: "maria", name: "Maria Reyes", initials: "MR", role: "Account Manager" },
      collaborators: [],
      checklist: [
        { id: "metrics", label: "Collect campaign metrics", completed: false },
        { id: "highlights", label: "Write performance highlights", completed: false },
        { id: "questions", label: "List client questions", completed: false },
      ],
      comments: [],
      versions: [],
      activity: [{ id: "activity-5", label: "Task assigned to Maria", actor: "Sarah Chen", createdAt: "Today · 9:35 AM" }],
    },
  ],
}
